apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: evershop  # Specify your namespace here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-storage
        resources:
          requests:
            memory: "256Mi"      # Minimum memory requested
            cpu: "250m"          # Minimum CPU requested
          limits:
            memory: "512Mi"      # Maximum memory allowed
            cpu: "500m"          # Maximum CPU allowed
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
