apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: evershop  # Specify your namespace here
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
