apiVersion: v1
kind: Service
metadata:
  name: evershop-service
  namespace: evershop  # Specify your namespace here
spec:
  selector:
    app: evershop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: evershop  # Specify your namespace here
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
