apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: evershop-app-hpa
  namespace: evershop  # Specify the same namespace as your deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: evershop-app  # Must match the name of your deployment
  minReplicas: 1          # Minimum number of replicas
  maxReplicas: 2         # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Target CPU utilization percentage
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70  # Target memory utilization percentage
