apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  labels:
    k8s-app: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: node-exporter
  template:
    metadata:
      labels:
        k8s-app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:latest
        ports:
          - containerPort: 9100
        volumeMounts:
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: sysfs
            mountPath: /host/sys
            readOnly: true
          - name: mount
            mountPath: /host/mnt
            readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
            type: Directory
        - name: sysfs
          hostPath:
            path: /sys
            type: Directory
        - name: mount
          hostPath:
            path: /mnt
            type: Directory

