apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: evershop
spec:
  replicas: 1  # Deploy 3 pods
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app-postgres
                operator: In
                values:
                - postgres
      volumes:
      - name: postgres-storage-new
        persistentVolumeClaim:
           claimName: postgres-pvc-new