---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-new
  namespace: evershop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2