replicaCount: 3

image:
  repository: shubh301/my-evershop-image
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

env:
  NODE_ENV: production
  DB_HOST: postgres.evershop.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: postgres

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
