apiVersion: v1
kind: Service
metadata:
  name: evershop-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: evershop-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: evershop-app
